import { test, expect } from '@playwright/test'
import { DatabaseSync } from 'node:sqlite'
import { execFileSync } from 'node:child_process'
import { copyFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const fixture = path.resolve('../../.local/browser-fixture-v2')
test.beforeAll(async () => {
  execFileSync('ffmpeg', ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=blue:s=320x240:r=24', '-t', '4', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-threads', '1', '-movflags', '+faststart', path.join(fixture, 'media/stage6-video.mp4')])
  await writeFile(path.join(fixture, 'media/stage6-broken.mkv'), 'unsupported fixture')
  await copyFile(path.join(fixture, 'cache/palette-1.jpg'), path.join(fixture, 'media/stage6-image.jpg'))
  const db = new DatabaseSync(path.join(fixture, 'fixture.db'))
  db.function('luma_key', { deterministic: true }, (value: string) => value.normalize('NFC').toUpperCase())
  db.function('luma_reverse', { deterministic: true }, (value: string) => [...value].reverse().join(''))
  db.function('luma_ticks', { deterministic: true }, (value: string) => BigInt(Date.parse(value)) * 10000n + 621355968000000000n)
  try {
    for (const [id, name, type, mime, extension, date] of [[1499, 'stage6-image.jpg', 'image', 'image/jpeg', '.jpg', '03'], [1495, 'stage6-video.mp4', 'video', 'video/mp4', '.mp4', '02'], [1490, 'stage6-broken.mkv', 'video', 'video/x-matroska', '.mkv', '01']] as const) {
      db.prepare('UPDATE Media SET FolderId=2,FileName=?,RelativePath=?,PathKey=?,MediaType=?,MimeType=?,Extension=?,ModifiedAt=?,EffectiveDate=? WHERE Id=?').run(name, name, name, type, mime, extension, `2026-04-${date}T00:00:00Z`, `2026-04-${date}T00:00:00Z`, id)
    }
  } finally { db.close() }
})

test('viewer zoom, rotation, horizontal swipe and desktop motion', async ({ page }) => {
  await page.goto('/?q=stage6')
  await page.getByTestId('media-cell').first().click()
  const viewer = page.getByRole('dialog')
  await expect(viewer).toBeVisible()
  await expect(page.locator('.motion-media')).toHaveCSS('animation-name', 'luma-media-in')
  await page.keyboard.press('+')
  await viewer.getByRole('button', { name: 'More options' }).click()
  const options = page.getByRole('dialog', { name: 'View options' })
  await expect(options.getByRole('button', { name: 'Reset zoom' })).toHaveText('125%')
  await options.getByRole('button', { name: 'Rotate', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(options).toHaveCount(0)
  await expect(viewer.getByRole('img')).toBeVisible()
  await expect.poll(() => viewer.getByRole('img').evaluate(img => img.parentElement!.style.transform)).toContain('rotate(90deg)')
  await viewer.getByRole('button', { name: 'More options' }).click()
  await options.getByRole('button', { name: 'Reset zoom' }).click()
  await page.keyboard.press('Escape')
  await expect(viewer.getByRole('button', { name: 'Next item' })).toBeEnabled()
  const bounds = await viewer.getByRole('img').boundingBox()
  await page.mouse.move(bounds!.x + bounds!.width * 0.7, bounds!.y + bounds!.height * 0.5)
  await page.mouse.down()
  await page.mouse.move(bounds!.x + bounds!.width * 0.3, bounds!.y + bounds!.height * 0.5, { steps: 8 })
  await page.mouse.up()
  await expect(viewer.locator('video')).toHaveCount(1)
  await page.screenshot({ path: `test-results/stage6-video-${test.info().project.name}.png` })
})

test('native video plays, seeks, changes speed and offers external access on failure', async ({ page }) => {
  await page.goto('/?q=stage6-video')
  await page.getByTestId('media-cell').first().click()
  const video = page.locator('video')
  await expect.poll(() => video.evaluate(v => v.readyState)).toBeGreaterThanOrEqual(2)
  const volume = page.getByRole('slider', { name: 'Volume', exact: true })
  await volume.focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await expect.poll(() => video.evaluate(v => v.volume)).toBe(0.05)
  await page.getByRole('button', { name: 'Mute', exact: true }).click()
  await expect.poll(() => video.evaluate(v => v.muted)).toBe(true)
  await page.getByRole('button', { name: 'Unmute', exact: true }).click()
  await expect.poll(() => video.evaluate(v => v.muted)).toBe(false)
  await page.getByRole('slider', { name: 'Seek', exact: true }).focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await expect.poll(() => video.evaluate(v => v.currentTime)).toBeGreaterThanOrEqual(0.1)
  await video.evaluate(v => v.play())
  await expect.poll(() => video.evaluate(v => v.currentTime)).toBeGreaterThan(0)
  await video.evaluate(v => { v.currentTime = 2 })
  await expect.poll(() => video.evaluate(v => v.currentTime)).toBeGreaterThanOrEqual(2)
  await page.getByRole('button', { name: 'Playback speed' }).click()
  expect(await video.evaluate(v => v.playbackRate)).toBe(1.5)
  await page.getByRole('button', { name: 'Close viewer' }).click()
  await expect(video).toHaveCount(0)
  await page.goto('/?q=stage6-broken')
  await page.getByTestId('media-cell').first().click()
  await expect(page.getByRole('status')).toContainText('external player')
  await page.getByRole('button', { name: 'More options' }).click()
  await expect(page.getByRole('button', { name: 'Copy stream URL' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download' })).toHaveAttribute('href', /download=true/)
  await expect(page.getByRole('link', { name: 'Open original' })).toHaveCount(0)
})

test('reels preserve query, bound media, auto-scroll, stop inactive playback and return to gallery', async ({ page }) => {
  await page.goto('/?q=stage6&order=desc')
  await expect(page.getByTestId('media-cell')).toHaveCount(3)
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Reels', exact: true }).click()
  const reels = page.getByRole('region', { name: 'Reels', exact: true })
  await expect(reels.locator('video')).toHaveCount(1)
  await expect(page).toHaveURL(/mediaType=video/)
  await expect(page).toHaveURL(/q=stage6/)
  await expect(reels.getByText('luma')).toBeVisible()
  await reels.getByRole('button', { name: 'Reels menu' }).click()
  await reels.getByRole('button', { name: 'Auto-scroll' }).click()
  await expect(reels.getByRole('button', { name: 'Auto-scroll' })).toHaveAttribute('aria-pressed', 'true')
  const old = await reels.locator('video').elementHandle()
  await expect.poll(() => old!.evaluate(v => v.paused)).toBe(false)
  const seek = reels.getByRole('slider', { name: 'Seek video', exact: true })
  await seek.focus()
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await expect(seek).toHaveAttribute('aria-valuetext', /of 0:04/)
  await reels.getByRole('button', { name: 'Auto-scroll' }).click()
  await reels.getByRole('button', { name: 'Next', exact: true }).click()
  await expect.poll(() => old!.evaluate(v => v.paused && !v.getAttribute('src'))).toBe(true)
  await expect(reels.locator('video')).toHaveCount(1)
  await expect(reels.getByRole('status')).toContainText('external player')
  expect(await reels.locator('img,video').count()).toBeLessThanOrEqual(1)
  expect(await reels.locator('link[rel=preload]').count()).toBeLessThanOrEqual(1)
  await page.screenshot({ path: `test-results/stage6-reels-${test.info().project.name}.png` })
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Library', exact: true }).click()
  await expect(page.getByTestId('media-cell')).toHaveCount(3)
  await expect(page).toHaveURL(/q=stage6/)
  await expect(page).not.toHaveURL(/mediaType=video/)
})

test('Back closes nested details then viewer then returns to libraries', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Open Sample library', exact: true }).click()
  await page.getByTestId('media-cell').first().click()
  await page.getByRole('button', { name: 'Media details' }).click()
  await expect(page.locator('[role=dialog]')).toHaveCount(2)
  await page.goBack()
  await expect(page.locator('[role=dialog]')).toHaveCount(1)
  await page.goBack()
  await expect(page.locator('[role=dialog]')).toHaveCount(0)
  await expect(page.getByTestId('media-cell').first()).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Your libraries' })).toBeVisible()
})

test('mobile pinch zoom and pan retain swipe navigation for images and videos', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Physical touch interaction')
  await page.goto('/?q=stage6')
  await page.getByTestId('media-cell').first().click()
  const viewer = page.getByRole('dialog')
  const bounds = await viewer.getByRole('img').boundingBox()
  const x = bounds!.x + bounds!.width / 2
  const y = bounds!.y + bounds!.height / 2
  const session = await page.context().newCDPSession(page)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x - 30, y, id: 0 }, { x: x + 30, y, id: 1 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 70, y, id: 0 }, { x: x + 70, y, id: 1 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await viewer.getByRole('button', { name: 'More options' }).click()
  const options = page.getByRole('dialog', { name: 'View options' })
  await expect(options.getByRole('button', { name: 'Reset zoom' })).not.toHaveText('100%')
  await page.keyboard.press('Escape')
  await expect(options).toHaveCount(0)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 40, y: y + 40, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => viewer.getByRole('img').evaluate(img => img.parentElement!.style.transform)).not.toContain('translate(0px, 0px)')
  await viewer.getByRole('button', { name: 'More options' }).click()
  await options.getByRole('button', { name: 'Reset zoom' }).click()
  await page.keyboard.press('Escape')
  await expect(options).toHaveCount(0)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x + 80, y, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 80, y, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(viewer.locator('video')).toHaveAttribute('src', '/api/media/1495/original')
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x + 80, y, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 80, y, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(viewer.locator('video')).toHaveAttribute('src', '/api/media/1490/original')
  await viewer.getByRole('button', { name: 'Close viewer' }).click()
  await expect(viewer).toBeHidden()
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Reels', exact: true }).click()
  const reels = page.getByRole('region', { name: 'Reels', exact: true })
  await expect(reels.locator('video')).toHaveAttribute('src', '/api/media/1495/original')
  const reelBounds = await reels.locator('video').boundingBox()
  const reelX = reelBounds!.x + reelBounds!.width / 2
  const reelY = reelBounds!.y + reelBounds!.height / 2
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: reelX, y: reelY + 80, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: reelX, y: reelY - 80, id: 0 }] })
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(reels.locator('video')).toHaveAttribute('src', '/api/media/1490/original')
})


